language: go
go:
    - 1.5.x
    - 1.6.x
    - 1.7.x
    - tip
before_install:
    - go get github.com/hirochachacha/go-test-reporter
script:
    - $HOME/gopath/bin/go-test-reporter -testflags="-tags gofuzz -race -v"
